language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
  - gem update cocoapods
xcode_workspace: HLLFont.xcworkspace
xcode_scheme: HLLFontDemo
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
